# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:44
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coment_Publi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField(blank=True, verbose_name='comentario')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('texto', models.TextField(blank=True, verbose_name='texto')),
                ('anexo', models.FileField(blank=True, upload_to=core.models.user_directory_path)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('area', models.ManyToManyField(to='core.Obt_Estudo')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coment_publi',
            name='publi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publicacao'),
        ),
        migrations.AddField(
            model_name='coment_publi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
