# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170518_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('texto', models.TextField(blank=True, verbose_name='texto')),
                ('area', models.ManyToManyField(to='core.Obt_Estudo')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resp_Forum_Duvida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.TextField(blank=True, verbose_name='resposta')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('melhor_resposta', models.BooleanField(default=False)),
                ('forum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Forum_Duvida')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
