# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:16
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170519_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment_publi',
            name='coment',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='coment_publi',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AlterField(
            model_name='coment_ublicacao_grupo_de_estudo',
            name='coment',
            field=models.TextField(blank=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='coment_ublicacao_grupo_de_estudo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AlterField(
            model_name='forum_duvida',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_altera',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Alteracao'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagem_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_profileimage, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='anexo',
            field=models.FileField(blank=True, upload_to=core.models.user_directory_path, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='publicacao_grupo_de_estudo',
            name='anexo',
            field=models.FileField(blank=True, upload_to=core.models.user_directory_path, verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='publicacao_grupo_de_estudo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AlterField(
            model_name='publicacao_grupo_de_estudo',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='resp_forum_duvida',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AlterField(
            model_name='resp_forum_duvida',
            name='melhor_resposta',
            field=models.BooleanField(default=False, verbose_name='Melhor_Resposta'),
        ),
        migrations.AlterField(
            model_name='resp_forum_duvida',
            name='resp',
            field=models.TextField(blank=True, verbose_name='Resposta'),
        ),
    ]
