# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170519_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coment_ublicacao_Grupo_de_Estudo',
            new_name='Coment_Publicacao_Grupo_de_Estudo',
        ),
    ]
