# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170602_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtes', models.ImageField(blank=True, null=True, upload_to='user_directory_profileimage', verbose_name='Imagem de Perfil')),
            ],
        ),
    ]
