# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-04 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_classname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassName',
        ),
    ]
