# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170605_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo_de_estudo',
            name='participantes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
