# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 17:45
from __future__ import unicode_literals

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170605_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo_de_estudo',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='grupo_de_estudo',
            name='area',
            field=models.ManyToManyField(to='core.Obt_Estudo', verbose_name='Objeto de Estudo'),
        ),
        migrations.AlterField(
            model_name='grupo_de_estudo',
            name='imagem_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_profileimage, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='grupo_de_estudo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo do Grupo'),
        ),
        migrations.AlterField(
            model_name='resp_forum_duvida',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Cadastro'),
        ),
        migrations.AlterField(
            model_name='resp_forum_duvida',
            name='melhor_resposta',
            field=models.BooleanField(default=False, verbose_name='Melhor Resposta'),
        ),
    ]
