# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170605_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo_de_estudo',
            old_name='bio',
            new_name='desc',
        ),
    ]
