# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170605_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment_publi',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='coment_publicacao_grupo_de_estudo',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='forum_duvida',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='publicacao_grupo_de_estudo',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='resp_forum_duvida',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
    ]
