# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170607_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='coment_publi',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AddField(
            model_name='publicacao',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
    ]
