# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_edituser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguidor',
            name='amigos',
        ),
        migrations.AddField(
            model_name='seguidor',
            name='amigos',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
