# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_publicacao_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment_publi',
            name='perfil',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AlterField(
            model_name='coment_publicacao_grupo_de_estudo',
            name='perfil',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AlterField(
            model_name='forum_duvida',
            name='perfil',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AlterField(
            model_name='publicacao_grupo_de_estudo',
            name='perfil',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
        migrations.AlterField(
            model_name='resp_forum_duvida',
            name='perfil',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='core.Perfil'),
        ),
    ]
