# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170622_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_duvida',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='core.Obt_Estudo'),
        ),
    ]
